[package]
name = "crona"
version = "0.1.0"
authors = ["chiyoku <chiyokuoni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
bincode = "1.2.1"
clap = "2.33.1"